import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.xml.transform.Result;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.*;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aet00
 */
public class EnterSearchTerm extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form RegisterForm
     */
    public EnterSearchTerm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeightUnits = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new JLabel();
        jLabelClose = new JLabel();
        jLabelMinimize = new JLabel();
        jPanel2 = new javax.swing.JPanel();
        jJButtonSearch = new javax.swing.JButton();
        jJButtonMenu = new javax.swing.JButton();
        jSearchTerm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new Color(248, 148, 6));

        jLabelTitle.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new Color(255, 255, 255));
        jLabelTitle.setText("Search Engine");

        jLabelClose.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                System.exit(1);
            }
        });

        jLabelMinimize.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinimize.setForeground(new Color(255, 255, 255));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));


        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitle)
                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimize)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMinimize))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new Color(44, 62, 80));


        jJButtonSearch.setBackground(new Color(192, 57, 43));
        jJButtonSearch.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jJButtonSearch.setForeground(new Color(255, 255, 255));
        jJButtonSearch.setText("Search");
        jJButtonSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jJButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                try {
                    jJButtonSearchCreateActionPerformed(evt);
                } catch (IOException | InterruptedException e) {
                    e.printStackTrace();
                }
            }


			private void jJButtonSearchCreateActionPerformed(ActionEvent evt) throws IOException, InterruptedException {

                WordCount.searchTerm = jSearchTerm.getText();
                System.out.println(WordCount.searchTerm);
                WordCount.searchForTerm();
                //Results r = new Results();
               // r.setVisible(true);
                Desktop d = Desktop.getDesktop();
                File f = new File("java-version.log");
                d.open(f);

			}



        });

        jJButtonMenu.setBackground(new Color(192, 57, 43));
        jJButtonMenu.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jJButtonMenu.setForeground(new Color(255, 255, 255));
        jJButtonMenu.setText("Menu");
        jJButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jJButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                try {
                    jJButtonMenuCreateActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }


            private void jJButtonMenuCreateActionPerformed(ActionEvent evt) throws IOException, InterruptedException {
                SearchAction m = new SearchAction();
                m.setVisible(true);
                hideCur();

            }



        });
        jSearchTerm.setBackground(new Color(108, 122, 137));
        jSearchTerm.setFont(new Font("Tahoma", 0, 16)); // NOI18N
        jSearchTerm.setForeground(new Color(228, 241, 254));

        jJButtonMenu.setBackground(new Color(108, 122, 137));
        jJButtonMenu.setFont(new Font("Tahoma", 0, 16)); // NOI18N
        jJButtonMenu.setForeground(new Color(228, 241, 254));


        JLabel lblEnterSearch = new JLabel();
        lblEnterSearch.setText("Enter Search Term");
        lblEnterSearch.setForeground(new Color(236, 240, 241));
        lblEnterSearch.setFont(new Font("Tahoma", Font.PLAIN, 20));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(103)
        					.addComponent(jSearchTerm, 294, 294, 294))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(158)
        					.addComponent(lblEnterSearch, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(112, Short.MAX_VALUE))
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(150, Short.MAX_VALUE)
        			.addComponent(jJButtonSearch, GroupLayout.PREFERRED_SIZE, 215, GroupLayout.PREFERRED_SIZE)
        			//.addGap(40)
                    .addComponent(jJButtonMenu, GroupLayout.PREFERRED_SIZE, 215, GroupLayout.PREFERRED_SIZE)
                    .addGap(0))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        			.addGap(69)
        			.addComponent(lblEnterSearch, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
        			.addComponent(jSearchTerm, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(40)
        			.addComponent(jJButtonSearch, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        			//.addGap(40)
                    .addComponent(jJButtonMenu, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                    .addGap(40))
        );
        jPanel2.setLayout(jPanel2Layout);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jJButtonMenuSearchCreateActionPerformed(ActionEvent evt) {
    }

    private void hideCur() {
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterSearchTerm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterSearchTerm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterSearchTerm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterSearchTerm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterSearchTerm().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup HeightUnits;
    private javax.swing.JButton jJButtonSearch;
    private javax.swing.JButton jJButtonMenu;
    private JLabel jLabelClose;
    private JLabel jLabelTitle;
    private JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jSearchTerm;
    
}
