import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aet00
 */
public class SelectFiles extends javax.swing.JFrame {
    WordCount w = new WordCount();
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form RegisterForm
     */
    public SelectFiles() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeightUnits = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new JLabel();
        jLabelClose = new JLabel();
        jLabelMinimize = new JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new JLabel();
        jFile1 = new javax.swing.JTextField();
        jJButtonLoad = new javax.swing.JButton();
        jLabel3 = new JLabel();
        jLabel2 = new JLabel();
        jFile2 = new javax.swing.JTextField();
        jFile3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new Color(248, 148, 6));

        jLabelTitle.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new Color(255, 255, 255));
        jLabelTitle.setText("Search Engine");

        jLabelClose.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                System.exit(1);
            	//jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMinimize.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinimize.setForeground(new Color(255, 255, 255));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
//        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jLabelMinimizeMouseClicked(evt);
//            }
//        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitle)
                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimize)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMinimize))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new Color(44, 62, 80));

        jLabel1.setFont(new Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new Color(236, 240, 241));
        jLabel1.setText("File 1:");

        jFile1.setBackground(new Color(108, 122, 137));
        jFile1.setFont(new Font("Tahoma", 0, 16)); // NOI18N
        jFile1.setForeground(new Color(228, 241, 254));
//        jTextFirstName.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextFirstNameActionPerformed(evt);
//            }
//        });

        jJButtonLoad.setBackground(new Color(192, 57, 43));
        jJButtonLoad.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jJButtonLoad.setForeground(new Color(255, 255, 255));
        jJButtonLoad.setText("Load Engine");
        jJButtonLoad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jJButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                try {
                    jButtonCancelActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }

            }

			private void jButtonCancelActionPerformed(ActionEvent evt) throws IOException {
                WordCount.path1 = jFile1.getText();
                WordCount.path2 = jFile2.getText();
                WordCount.path3 = jFile3.getText();
                System.out.println(WordCount.path1 + " " + WordCount.path2+ " " + WordCount.path3);
				//w.invertIndices();

                SearchAction searchActionGUI = new SearchAction();
                searchActionGUI.setVisible(true);
                hideCur();
                //SelectFiles.setVisible(false);
				
			}
        });
        /*
        jButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreateMouseClicked(evt);
            }
        });
        
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });
*/
        jLabel3.setFont(new Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new Color(236, 240, 241));
        jLabel3.setText("File 3:");

        jLabel2.setFont(new Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new Color(236, 240, 241));
        jLabel2.setText("File 2:");

        jFile2.setBackground(new Color(108, 122, 137));
        jFile2.setFont(new Font("Tahoma", 0, 16)); // NOI18N
        jFile2.setForeground(new Color(228, 241, 254));
//        jTextLastName.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextLastNameActionPerformed(evt);
//            }
//        });

        jFile3.setBackground(new Color(108, 122, 137));
        jFile3.setFont(new Font("Tahoma", 0, 16)); // NOI18N
        jFile3.setForeground(new Color(228, 241, 254));
//        jTextUsername.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextUsernameActionPerformed(evt);
//            }
//        });
        /*
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });
        */
        JLabel lblEnterFilePath = new JLabel();
        lblEnterFilePath.setText("Enter File Path");
        lblEnterFilePath.setForeground(new Color(236, 240, 241));
        lblEnterFilePath.setFont(new Font("Tahoma", Font.PLAIN, 20));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(31)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1)
        				.addComponent(jLabel2)
        				.addComponent(jLabel3))
        			.addGap(65)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jFile3, 294, 294, 294)
        				.addComponent(jFile2, 294, 294, 294)
        				.addComponent(jFile1, 294, 294, 294))
        			.addContainerGap(64, Short.MAX_VALUE))
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(179, Short.MAX_VALUE)
        			.addComponent(lblEnterFilePath, GroupLayout.PREFERRED_SIZE, 155, GroupLayout.PREFERRED_SIZE)
        			.addGap(175))
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(169, Short.MAX_VALUE)
        			.addComponent(jJButtonLoad, GroupLayout.PREFERRED_SIZE, 215, GroupLayout.PREFERRED_SIZE)
        			.addGap(125))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(13)
        			.addComponent(lblEnterFilePath, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(jFile1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(jFile2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(jFile3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(39)
        			.addComponent(jJButtonLoad, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectFiles().setVisible(true);
            }
        });
    }
    private void hideCur() {
        this.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup HeightUnits;
    private javax.swing.JButton jJButtonLoad;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel jLabel2;
    private JLabel jLabelClose;
    private JLabel jLabelTitle;
    private JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jFile1;
    private javax.swing.JTextField jFile2;
    private javax.swing.JTextField jFile3;
    
}
